### PR TITLE
Feat+Fix: Refactor m3u download, new dark mode, file icon

### PR DESCRIPTION
**Pull request by rayanfer32**
… develop

### CODE REVIEW

**Comment by ManOfInfinity** [comment]
Hi,
I was just trying to deploy your forked one,
I'm getting this error

image

**Comment by rayanfer32** [comment]
Your pip3 install has failed.
If you are using a bash repl , then run python3 in command line and it will ask to install it. Choose python39full

**Comment by ManOfInfinity** [comment]
I'm using this method

https://repl.it/github/rayanfer32/tg-index

Update: post installation pip
getting below error

image

image

**Comment by ManOfInfinity** [comment]
Hi...
Will you please update this?

**Comment by rayanfer32** [comment]
This must be working right

**Comment by ManOfInfinity** [comment]
it's working. and yes I checked its using bash.

could you pls check this once?
and if you have any tg handle give username better to communicate.

**Pull request merged**
